# Install Redis stack in the selected namespace.
#
# To access the Redis stack web UI, launch the following command:
# kubectl port-forward svc/redis-stack 8001:8001
# Then open the URL http://localhost:8001 in a browser on the same computer as the port forwarding
# command above was started.
#
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis-stack
  # Namespace in which the Redis Helm chart job will be run.
  namespace: "{{ k8s_namespace }}"
spec:
  # Helm chart repository. Does not have to be defined in the K3S cluster prior to deploy of this configuration.
  repo: https://redis-stack.github.io/helm-redis-stack/
  # Name of Helm chart to deploy
  chart: redis-stack
  # Namespace to which Redis will be deployed.
  targetNamespace: "{{ k8s_namespace }}"
  # Modified configuration of the Helm chart.
  valuesContent: |-
    architecture: standalone
    global:
      redis:
        password: "secret!"
      ha:
        enabled: false
---
# Create a secret that contain the above Redis password.
apiVersion: v1
data:
  redis-password: c2VjcmV0IQ==
kind: Secret
metadata:
  name: redis
  namespace: "{{ k8s_namespace }}"
type: Opaque
