# Create the Dapr state store component backed by Redis for the development environment.
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: development
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      secretKeyRef:
        name: redis
        key: redis-password
---
# Create Dapr pub/sub message broker component backed by Redis for the development environment.
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: development
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis-master.dapr-system.svc.cluster.local:6379
    - name: redisPassword
      secretKeyRef:
        name: redis
        key: redis-password
